### PR TITLE
Default public

### PR DESCRIPTION
**Pull request by michellej**
Updating copy

### CODE REVIEW

**Comment by klhaskins28** [comment]
Awesome

**Comment by apit8147** [comment]
on

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by zmyat** [comment]
M

**Comment by lyntaurus23** [comment]
Hope to open/see the stuff i want to see.

**Comment by WINSEONJUNIOR** [comment]
open

**Comment by ScubaDome** [comment]
Show me

**Pull request closed without merging**
