### PR TITLE
Terms of Service and Privacy Policy update for the new paid products

### PR DESCRIPTION
**Pull request by wjrosa**
This update on our terms is needed to archive the latest information related to our paid products before the new features are released on our main pages.

### CODE REVIEW

**Comment by Brainz0** [comment]
How to update it ?

**Comment by rewkii** [comment]
> This update on our terms is needed to archive the latest information related to our paid products before the new features are released on our main pages.

**Comment by rewkii** [comment]
Good

**Comment by rewkii** [comment]
Good

**Pull request closed without merging**
