### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Armandd123**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by Armandd123** [comment]
Y

**Comment by Armandd123** [comment]
K

**Comment by Armandd123** [comment]
.

**Comment by rhino212k** [comment]
Bksfnc

**Pull request closed without merging**
