### PR TITLE
update terms of service

### PR DESCRIPTION
**Pull request by jamalirving**
This simply updates the terms of service to the latest version that Tumblr has.

### CODE REVIEW

**Comment by wjrosa** [comment]
Just to confirm, this is the version being replaced by your other PR, right? Not the latest one? If that's the case, LGTM 👍

**Review by wjrosa — APPROVED** [review]

**Comment by jamalirving** [comment]
> Just to confirm, this is the version being replaced by your other PR, right? Not the latest one? If that's the case, LGTM 👍

@wjrosa correct, this version replaces my other PR that I had closed.

**Review by mamoru4649 — APPROVED** [review]

**Review by KishoreganjpostNewspaper — APPROVED** [review]

**Review by xnightmarex780 — APPROVED** [review]

**Comment by luluthefnafwolf** [comment]
Unsubscribe

**Comment by 0b10011** [comment]
We've merged some PRs since this was originally opened, so I'm closing in favor of those. They should have gotten all of the changes here in the sync.

**Pull request closed without merging**
