### PR TITLE
Update api-license-agreement.txt

### PR DESCRIPTION
**Pull request by Techfolio**
Added the word "master" to service agreement to help clarify the acronym MSA.

### CODE REVIEW

**Comment by brinto** [comment]
Checked

**Comment by McNair34** [comment]
Master

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by against68** [comment]
I love porn

**Pull request closed without merging**
